name: SimpleAutomessage
main: com.carlgo11.simpleautomessage.Main
version: 1.0.3
description: Broadcasts a message to all players
author: Carlgo11
commands:
   SimpleAutomessage:
     aliases: [AutoMessage, Simplemsg]
     description: Main command of SimpleAutoMessage.