name: SimpleAutoMessage
main: com.carlgo11.simpleautomessage.Main
version: 1.0.5
description: Auto-announcer plugin
author: Carlgo11
website: http://www.carlgo11.com/
commands:
   SimpleAutomessage:
     aliases: [AutoMessage, Simplemsg, automsg]
     description: Main command of SimpleAutoMessage.
     
permissions:
  simpleAutoMessage.seemsg:
    default: true
    description: Permission to see the messages broadcasted by SimpleAutomessage
  simpleAutoMessage.simpleautomessage:
    default: op
    description: permission to use /simpleautomessage 
  simpleAutoMessage.simpleautomessage.reload:
    default: op
    description: permission to use /simpleautomessage reload
  simpleAutoMessage.simpleautomessage.list:
    default: op
    description: permission to use /simpleautomessage reload
  simpleAutoMessage.*:
    default: op
    description: gives the player all the SimpleAutoMessage permissions
    children:
      simpleAutoMessage.simpleautomessage: true
      simpleAutoMessage.simpleautomessage.reload: true
      simpleAutoMessage.simpleautomessage.list: true
      simpleAutoMessage.seemsg: true